### ISSUE TITLE
no bbox result when run yolov4 in Jetson NX

### ISSUE THREAD

**Issue by Ashing00** [Tianxiaomo/pytorch-YOLOv4#102] opened 2020-06-10 13:50 UTC
I run yolov4  on Jetson NX,but can not get correct bbox 
use darknet2onnx.py to convert yolov4.cfg and yolov4.weight.
then convert to yolov4.trt 
when run demo_trt.py yolov4.trt dog.jpg 416 416
get below result 
/-----------------------------------------
Reading engine from file yolov4-416.trt
Shape of the network input:  (1, 3, 416, 416)
Length of inputs:  1
Len of outputs:  9
-----------------------------------
    TRT inference time: 0.132841
-----------------------------------
-----------------------------------
     get_region_boxes : 0.002494
                  nms : 0.007532
   post process total : 0.010035
-----------------------------------
truck: 0.980625
dog: 0.999999
bicycle: 1.000000
/----------------------------------
but no bbox in the predictions_trt.jpg
I print the <trt_outputs> check the  in demo_trt.pyp line 151
get below value

/-------------------------------------------
[array([1.0889691e-04, 3.5633548e-05, 2.2827997e-05, ..., 3.6400868e-04,
       2.5315638e-04, 3.8831109e-05], dtype=float32), array([7.9498291e-03, 1.0000000e+01, 1.8692017e-02, ..., 1.0000000e+01,
       4.8004150e-02, 3.5705566e-02], dtype=float32), array([4.1845703e-01, 1.3954163e-02, 8.3496094e-02, ..., 6.1416626e-03,
       8.0537796e-04, 1.5139580e-04], dtype=float32), array([4.0929112e-06, 8.2035322e-06, 6.0963603e-06, ..., 4.5659704e-06,
       2.2603242e-06, 8.5792357e-07], dtype=float32), array([ 0.02755033, 10.        ,  0.07742122, ..., 10.        ,
        0.10579979,  0.13517565], dtype=float32), array([3.6437038e-01, 1.7008580e-02, 5.5334978e-02, ..., 7.9847518e-03,
       2.9890699e-04, 2.4877247e-04], dtype=float32), array([1.04296953e-06, 2.07851699e-05, 3.73435687e-05, 3.64785374e-05,
 ......................
, array([0.02295261, 0.00861033, 0.12978163, ..., 0.00506801, 0.00085359,
       0.00099795], dtype=float32), array([ 0.06552535, 10.        ,  0.24504207, ..., 10.        ,
        0.5348558 ,  0.55544066], dtype=float32)]
//-------------------------------------------------------------------------------
I got some wrong value==> 10. ..10.
But it is really strange in my PC RTX2070 TRV7.0.0.11 is ok ,no problem.
I have no idea about it.

**Comment by ersheng-ai** [comment] 2020-06-11 02:15
Thank you for your information.
TensorRT + yolov4 have not been verified on embedded (arm64) platform yet.
We will look into it.

**Comment by ersheng-ai** [comment] 2020-06-16 02:55
We have reproduced similar faults on Jetson AGX Xavier with Jetpack 4.4 DP installed.
Further investigation is on going.

**Comment by Ashing00** [comment] 2020-06-17 15:28
@ersheng-ai 

better,but still incorrect.on NX.

[https://photos.app.goo.gl/FzcxkeURKM3RAyZW8](url)

**Comment by kskrueger** [comment] 2020-06-17 23:54
I am having a similar issue of the output boxes not being in the correct position when running the network on Xavier NS. I think the issue may be related to the process of converting Darknet weights to .onnx format with the PyTorch script.

While running the conversion script:
`python3 demo_darknet2onnx.py yolov4.cfg yolov4_best.weights Test.png 1`

This warning occurs, which seems to be causing the issue with the boxes not lining up later if there is a constant value being set in the network during conversion possibly.
`TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!`

Is there a better way to convert the YoloV4 Darknet weights to .onnx format?

**Comment by ersheng-ai** [comment] 2020-06-18 02:08
Bounding boxes by onnx model and tensorrt engine are both verified to be correct on X86 + Tesla T4 platform.
We suspect tensorrt from Jetpack 4.4 DP resolves the onnx model incorrectly.

All y coordinates of bounding boxes are wrong when I was testing Jetpack 4.4 DP on Jetson AGX Xavier
![result](https://user-images.githubusercontent.com/62684483/84969236-da83fa00-b14a-11ea-9d94-93b1dca25f5b.jpg)

Investigation is underway.
There would be a new Jetpack release end this month and we will verify that version as well.
Hope this issue is fixed by the new version.

**Comment by zoidburg** [comment] 2020-06-29 07:18
I met the same problem while testing the trt engine inference.  The onnx demo worked fine, the trtexec process seemed ok 
![predictions_onnx](https://user-images.githubusercontent.com/11624459/85983595-5834e900-ba1a-11ea-96f7-fbbd6f2b2a13.jpg)

but the trt demo predicted invalid y coord, just like the pictures posted before.
![predictions_trt](https://user-images.githubusercontent.com/11624459/85983579-510ddb00-ba1a-11ea-8eb9-052b56bf688a.jpg)

I tested in ngc docker image nvcr.io/nvidia/tensorrt:20.06-py3, my GPU is P40, Driver Version: 440.64.00, CUDA Version: 11.0 

so do you have any suggestions on debugging this problem?  Thank you @ersheng-ai

**Comment by ersheng-ai** [comment] 2020-06-29 07:25
@zoidburg 

Which TensorRT version are you using?

**Comment by zoidburg** [comment] 2020-06-29 07:30
nvcr.io/nvidia/tensorrt:20.06-py3 
ENV TENSORRT_VERSION=7.1.2.8
@ersheng-ai

**Comment by zoidburg** [comment] 2020-06-29 08:03
I tried to print the output of trt inference, the value corresponding to y cood seems invalid. Could this be the cause of the problem?

![image](https://user-images.githubusercontent.com/11624459/85988141-325f1280-ba21-11ea-964b-c0cd029e104f.png)

@ersheng-ai

**Comment by ersheng-ai** [comment] 2020-06-29 11:06
Try downloading TensorRT 7.1.3.4 from NVIDIA developer page.
You can select tar packages of TensorRT (**NOT** deb) because tar packages does not need installation procedures, so that it does not clash with the preinstalled one on the docker.

Tell me if this problem still persists for 7.1.3.4.

**Comment by 17702513221** [comment] 2020-06-29 11:57
我测试的tensorrt 7.1.3.4版本，问题仍然存在，cuda10.2 cudnn8

**Comment by zoidburg** [comment] 2020-06-30 01:13
TRT 7.0.0 seems ok, the inference works fine and I got the correct prediction result.

**Comment by ersheng-ai** [comment] 2020-06-30 03:02
Thank you for all your useful information.
We will investigate this problem and locate which layer TRT 7.1 handles wrongly.

**Comment by ersheng-ai** [comment] 2020-07-05 14:28
Please pull the latest source code and re-generate ONNX and trt engine file.
There are some slight updates in **`yolo_forward()`** method to bypass the defect of TensorRT 7.1

Original
```py
    # normalize coordinates to [0, 1]
    bx = bx / W
    by = by / H
    bw = bw / W
    bh = bh / H
```

Updated

```py
    # Shape: [batch, 2 * num_anchors, H, W]
    bx_bw = torch.cat((bx, bw), dim=1)
    # Shape: [batch, 2 * num_anchors, H, W]
    by_bh = torch.cat((by, bh), dim=1)

    # normalize coordinates to [0, 1]
    bx_bw /= W
    by_bh /= H
```

TensorRT 7.1 is now verified to be OK.

**Comment by ersheng-ai** [comment] 2020-07-08 03:10
TensorRT 7.1 of Jetpack 4.4 DP on Jetson is also verified to be okay.
I will close this issue.
Please re-open issues if you still have problems.

**Closed by ersheng-ai** 2020-07-08 03:10 UTC
Labels: bug

**Comment by wurongyuan** [comment] 2020-07-12 12:24
> I met the same problem while testing the trt engine inference. The onnx demo worked fine, the trtexec process seemed ok
> ![predictions_onnx](https://user-images.githubusercontent.com/11624459/85983595-5834e900-ba1a-11ea-96f7-fbbd6f2b2a13.jpg)
> 
> but the trt demo predicted invalid y coord, just like the pictures posted before.
> ![predictions_trt](https://user-images.githubusercontent.com/11624459/85983579-510ddb00-ba1a-11ea-8eb9-052b56bf688a.jpg)
> 
> I tested in ngc docker image nvcr.io/nvidia/tensorrt:20.06-py3, my GPU is P40, Driver Version: 440.64.00, CUDA Version: 11.0
> 
> so do you have any suggestions on debugging this problem? Thank you @ersheng-ai

hey, how to install onnxruntime at Jetson tx2 or other boards(arm64)?
Thank you.

**Comment by beizhengren** [comment] 2020-08-06 12:31
@kskrueger 
Hi, have you solved the problem?

**Comment by kskrueger** [comment] 2020-08-11 15:07
@beizhengren Yes, the boxes are working correctly now.
